# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages
warnings_are_errors: false

apt_packages:
 - libgmp3-dev
 - libmpfr-dev

r_packages:
 - dplyr
 - knitr
 - rmarkdown
 - psd
 - RColorBrewer
 - sapa
 - signal
 - testthat
 - covr
# - kelvin

r_github_packages:
 - abarbour/kelvin
 
notifications:
 email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
