# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

apt_packages:
 - libgmp3-dev
 - libmpfr-dev

r_binary_packages:
# until v2.0 binaries are on cran #  - kelvin
  - knitr
  - rmarkdown
  - psd
  - RColorBrewer
  - sapa
  - signal
  - testthat
  - covr
  - kelvin
 
notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
