# .travis.yml for kitagawa

language: r
warnings_are_errors: false
sudo: required

apt_packages:
 - libgmp3-dev
 - libmpfr-dev

r_binary_packages:
# until v2.0 binaries are on cran #  - kelvin
  - knitr
  - rmarkdown
  - psd
  - RColorBrewer
  - sapa
  - signal
  - testthat
  
r_github_packages:
  - jimhester/covr
  - abarbour/kelvin
  

notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
  - Rscript -e 'library(covr);codecov()'