# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: false
#latex: false

apt_packages:
 - libgmp3-dev
 - libmpfr-dev

r_packages:
# until psd 2.0 is on cran
# - psd
 - Bessel
 - kelvin
 - dplyr
 - knitr
 - formatR
 - rmarkdown
 - RColorBrewer
 - signal
 - testthat
 - covr

# - abarbour/kelvin
#   - stringi	   
r_github_packages:
   - gagolews/stringi
   - abarbour/psd
   
jobs:
  include:
  - r: devel
  - r: release
#  - r: 3.4
#  - r: 3.3
#  - r: 3.2
#  - r: 3.1
  
notifications:
 email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
