# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
#dist: trusty
cache: packages
warnings_are_errors: false
#latex: false

apt_packages:
 - libgmp3-dev
 - libmpfr-dev

r_github_packages:
# - abarbour/kelvin
   - gagolews/stringi
#   - abarbour/psd

r_packages:
#   - stringi	   
 - psd
 - Bessel
 - kelvin
 - dplyr
 - RColorBrewer
 - signal
 - knitr
 - formatR
 - rmarkdown
 - testthat
 - covr
   
jobs:
  include:
  - r: devel
  - r: release
  
notifications:
 email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
