# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
dist: trusty
cache: packages
warnings_are_errors: false
#latex: false

apt_packages:
 - libgmp3-dev
 - libmpfr-dev

#r_packages:
# - dplyr
# - knitr
# - rmarkdown
# - psd
# - RColorBrewer
# - sapa
# - signal
# - testthat
# - covr
# - kelvin

#r_github_packages:
# - abarbour/kelvin

jobs:
  include:
  - r: 3.1
    warnings_are_errors: false
  - r: 3.2
    warnings_are_errors: false
  - r: 3.3
  - r: 3.4
  - r: release
  - r: devel
  
notifications:
 email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
