%% HEAD from knitr template
%% /Users/abarbour/Library/textemplates
%% Thu Feb  7 18:24:57 PST 2013
\documentclass[10pt]{article}
%%
%% !Rnw weave = knitr
%% sweave fig help:
%% http://users.stat.umn.edu/~geyer/Sweave/foo.pdf
%%
% \VignetteIndexEntry{ResponseModels}
% \VignetteEngine{knitr}
%
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage[font=sf, labelfont={sf,bf}, margin=2cm]{caption}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{fancyvrb}
\usepackage{float}
\usepackage{geometry}
\geometry{verbose,tmargin=3cm,bmargin=5cm,lmargin=2.5cm,rmargin=2.5cm}
\usepackage{graphicx}
\usepackage{grffile}
\usepackage[pdfborder={0 0 0}]{hyperref}
\usepackage[utf8]{inputenc}
\usepackage{natbib}
\usepackage{makeidx}
\makeindex % comment to have no index
\usepackage{upquote}
\usepackage{url}
%
\author{Andrew J. Barbour}
\title{Demonstration of Well Response Functions}
\begin{document}
\maketitle
%\tableofcontents
%% BODY from knitr template
%\newcommand{\newcomm}[1]{#1}
%\renewcommand{\newcomm}[1]{#1}
%
\newcommand{\SC}[1]{\textsc{#1}}
\newcommand{\Rcmd}[1]{\texttt{#1}}
\newcommand{\bidxa}[1]{\index{#1}{\textbf{#1}}} 
\newcommand{\bidxb}[2]{\index{#2}{\textbf{#1}}} 
\newcommand{\idxa}[1]{\index{#1}{#1}} 
\newcommand{\idxb}[2]{\index{#2}{#1}} 
%
\begin{abstract}
abstract text
\end{abstract}
%
\section{Introduction}
Load the packages
<<eval=TRUE, echo=TRUE, label=PRELIM>>= 
library(signal, warn.conflicts=FALSE)
library(kitagawa, warn.conflicts=FALSE)
@

\section{Sealed well response}
\subsection{Strain: Kitagawa (2011)}
%
\citet{kitagawa2011}

\section{Open well response}
\subsection{Strain: Rojstaczer (1988)}
%
\citet{rojstaczer1988, rojstaczer1988b}

<<eval=TRUE, echo=TRUE, label=ROJRESP>>= 
# Some dummy parameters
z <- 1
Trans <- 1
Stor <- 1
Diffus <- Trans/Stor
# Nondimensional frequencies
Q <- 10**seq(-3,2,by=0.1) # == z**2 omega / 2 D
omega <- omega_norm(Q, z, Diffus, invert=TRUE) # == Q * 2 * Diffus / z**2
wrsp <- open_well_response(omega, T.=Trans, S.=Stor, z.=z, model = "rojstaczer", as.pressure=FALSE)
crsp <- wrsp[,2]
#
lQ <- log10(Q)
# Amplitude
As <- 0.05 # cm/nE
Gain <- Mod(crsp)
# Phase
Phs <- Arg(crsp) # will wrap to -pi/pi
uPhs <- signal::unwrap(Phs, tol=pi/30)
@

\begin{figure}[htb!]
\begin{center}
<<eval=TRUE, echo=FALSE, fig.height=7, fig.width=5.5, label=ROJRESPFIG>>=
par(mfrow=c(2,1), 
    mar=c(2.5,4,3.1,2), 
    oma=rep(0.1,4), 
    omi=rep(0.1,4), 
    las=1)

plot(lQ, Gain, type="l", ylim=c(0, 1.15),
     xaxt="n", yaxs="i",
     lwd=2,
     ylab="", #" (cm/nanostrain)", 
     xlab="", #Dimensionless frequency Q",
     main="")
log10_ticks()
mtext("Open Well Response: Harmonic Strain", font=2, line=1.5)
mtext("(a) Gain relative to static-confined areal strain response", adj=0)
#mtext(sprintf(" areal strain\nresponse: %.02f cm/ne",As), padj=1, adj=0.1, line=-1, cex=0.7)
par(mar=c(4,4,1.1,2))
plot(lQ, Phs*180/pi, type="l", lty=3, ylim=c(-190, -130), 
	 xaxt="n",
     ylab="degrees", xlab=expression("Dimensionless frequency," ~ Q ==z^2 * omega / 2 * D  ))
abline(h=-180, col="grey")
lines(lQ, uPhs*180/pi, type="l", lwd=2)
log10_ticks()
mtext("(b) Phase of pressure relative to strain", adj=0)
text(1.4, -140, "phase crossings", font=3, cex=0.8)
@
\caption{The response of an open well to harmonic areal strain using
the Rojstaczer model. Modified from \citet[][Fig.~3]{rojstaczer1988}.
Frequency is dimensionless, based on the well-depth $z$ and the diffusivity
$D$.}
\label{fig:tmp}
\end{center}
\end{figure}

%% TAIL from knitr template
\bibliographystyle{apalike}
\bibliography{REFS}

\printindex

\end{document}
