#
#	!! autogenerated !!
#
#	.sourceloads.R	
#	makeloads.sh	Wed Sep 26 21:04:07 PDT 2012
#	/Users/abarbour/nute.processing/development/kitagawa/rsrc
#
source("/Users/abarbour/nute.processing/development/kitagawa/rsrc/S3.R")
source("/Users/abarbour/nute.processing/development/kitagawa/rsrc/func_constants.R")
source("/Users/abarbour/nute.processing/development/kitagawa/rsrc/func_plot.R")
source("/Users/abarbour/nute.processing/development/kitagawa/rsrc/func_response.R")
source("/Users/abarbour/nute.processing/development/kitagawa/rsrc/func_utils.R")
