#
#	!! autogenerated !!
#
#	.sourceloads.R	
#	makeloads.sh	Wed Sep 26 14:49:16 PDT 2012
#	/Users/abarbour/kook.processing/R/dev/packages/kitagawa/rsrc
#
source("/Users/abarbour/kook.processing/R/dev/packages/kitagawa/rsrc/S3.R")
source("/Users/abarbour/kook.processing/R/dev/packages/kitagawa/rsrc/func_constants.R")
source("/Users/abarbour/kook.processing/R/dev/packages/kitagawa/rsrc/func_plot.R")
source("/Users/abarbour/kook.processing/R/dev/packages/kitagawa/rsrc/func_response.R")
source("/Users/abarbour/kook.processing/R/dev/packages/kitagawa/rsrc/func_utils.R")
